apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: myapp
spec:
  type: NodePort # For local testing with minikube or a lab cluster. In production, you might use Ingress.
  selector:
    app: webapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30080
