apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: jummy98/webappflask:latest # Replace with your Docker image name.
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: postgres.myapp.svc.cluster.local
        - name: DB_NAME
          value: mydb
        - name: DB_USER
          value: myuser
        - name: DB_PASSWORD
          value: mypassword
